# Where NNSVS is
nnsvs_root: "~/nnsvs"

### General settings.
## The name of singer
spk: "oniku_kurumi"

# Directory of Unzipped singing voice database
# PLEASE CHANGE THE PATH BASED ON YOUR ENVIRONMENT
db_root: "/mnt/d/NNSVS/db/OnikuKurumi/oniku_kurumi_utagoe_db_v1.1_declip_ecodeco_dither"

# exp tag(for managing experiments)
tag: "jp_qst_crazy_mono_006_193D"

## HTS-style question used for extracting musical/linguistic context from musicxml files
question_path: "./hed/jp_qst_crazy_mono_006_193D.hed"

# Output directory
out_dir: "./data"

## Songs to be excluded from trainig.
exclude_songs: []

### Pyinsy related settings.
## Sinsy dictionary directory
# This singing voice database contains the unvoiced vowels "I" and "U".
# To enable the unvoiced vowels, modified version of sinsy dictionary files
# are needed.
sinsy_dic: "./dic"

### Data preparation related settings.
## Song segmentation by silence durations.
# TODO: would be better to split songs by phrasal information in the musical scores
# Split song by silences (in sec)
segmentation_threshold: 0.4
# Min duration for a segment
# note: there could be some execptions (e.g., the last segment of a song)
segment_min_duration: 5.0
# Force split segments if long silence is found regardless of min_duration
force_split_threshold: 5.0
# Offset correction
# If True, offset is computed in an entire song
# otherwise offset is computed for each segment
global_offset_correction: False
offset_correction_threshold: 0.01
# Time-lag constraints to filter outliers
timelag_allowed_range: [-20, 19]
timelag_allowed_range_rest: [-40, 39]
# Audio sampling rate
# CAUTION: Changing sample_rate may affect the dimension number of acoustic features.
# DO NOT CHANGE this unless you know the relationship between the dim of bap and sample_rate.
sample_rate: 96000

###########################################################
#                DATA PREPARATION SETTING                 #
###########################################################


###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################

timelag_features: defaults
duration_features: defaults
acoustic_features: static_deltadelta

###########################################################
#                TRAINING SETTING                         #
###########################################################

# Models
# To customize, put your config or change ones in
# conf/train/{timelag,duration,acoustic}/ and
# specify the config name below
# NOTE: *_model: model definition, *_train: general train configs,
# *_data: data configs (e.g., batch size)

timelag_model: timelag_mdn
timelag_train: myconfig
timelag_data: myconfig

duration_model: duration_mdn
duration_train: myconfig
duration_data: myconfig

acoustic_model: acoustic_mdn
acoustic_train: myconfig
acoustic_data: myconfig

# Pretrained model dir (leave empty to disable)
pretrained_expdir:

###########################################################
#                SYNTHESIS SETTING                        #
###########################################################
timelag_synthesis: defaults
duration_synthesis: defaults
acoustic_synthesis: defaults

# latest.pth or best.pth
timelag_eval_checkpoint: latest.pth
duration_eval_checkpoint: latest.pth
acoustic_eval_checkpoint: latest.pth
